name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Test API
        uses: actions/checkout@v4
        run: go test ./...

      - name: Echo Go version
        run: (exit 0)
